### ISSUE TITLE
Gitter rooms cannot be searched

### ISSUE THREAD

**Issue by PhDyellow** [MathMarEcol/Welcome#22]
@jaseeverett 

@rosamard  was having trouble finding the MathMarEcol rooms.

As far as I can tell, there is no search within a community for private rooms. You need to know the url.

Once @rosamard had the url, she could add herself to the room.

The solution is to have a list of private gitter room urls in MathMarEcol/Welcome, or to make all the rooms public.

**Comment by PhDyellow** [comment]
There is a third option, someone already in the room adds new people to the room manually.

**Comment by C-Lawson** [comment]
Ditto. Can someone please add me? I can only get to the "Testing_public" room

**Comment by PhDyellow** [comment]
https://gitter.im/MathMarEcol/Testing_Gitter
https://gitter.im/MathMarEcol/RTipsTricksTrouble
https://gitter.im/MathMarEcol/Lab_chat
https://gitter.im/MathMarEcol/watson_data
https://gitter.im/MathMarEcol/OpenDataScience
https://gitter.im/MathMarEcol/General

**Comment by PhDyellow** [comment]
We are all on slack now.
