### ISSUE TITLE
Cloud Computing

### ISSUE THREAD

**Issue by PhDyellow** [MathMarEcol/Welcome#9]
@jaseeverett  

David Abramson is happy to meet with us and discuss needs.
<https://rcc.uq.edu.au/profile/104/david-abramson>

Presented by James Gallagher

Options

Amazon
:   S3, Glacier, AWS

Google
:   Google Cloud storage, Google Cloud

Microsoft
:   Azure, Azure blob storage

OpenStack
:   Not a provider, but lets anyone with hardware compete with Amazon,
    Google, Microsoft clouds

You can go with a server, which has OS, core, memory, and a local disk.

You can go "serverless", where your code is run without a whole OS and
no local disk, memory only.

Using containers and high level languages like python, you can switch
easily. BUT the most expensive thing you can do is download data from
provider storage to somewhere other than provider servers.

S3, Google Cloud Storage, Azure Blob Storage don't have a POSIX file
system. Everything is just a binary blob.

-   Pros
    -   Scales in parallel very well
    -   Easy to access over HTTP
    -   Persists when the VM is shut down
-   Cons
    -   Code needs to retry if a read fails, reads will always fail
        randomly
    -   No modify, you delete and replace
    -   changes are not available instantly, sometimes you get the old
        object
    -   Reading files works differently, you use HTTP rather than file
        access

Blob storage is for accessing some large files, accessing many small
files has too much overhead (use a DB)

Big files take time to cache to a local disk. You can request a subset
of a file, but you have to know ahead of time which subset you need,
which means calculating and storing metadata. James works with HDF5
files, which netCDF4 uses as a backend. HDF5 files can be subset so you
only read in what you want.

Always an admin effort to set up, you don't want files to be public and
available to all, because you get charged when someone downloads it.

James heard that having your own server is cheaper overall than using
s3, but small operators won't have the resources to set up a server
room, IT staff, configure software, pay for air-conditioning, etc. S3 is
really good for trying something out, think renting vs owning.

There is a Zarr format, which is like a deconstructed HDF5 format, but
it is python only for now.

We could go with any of these options, but we would be paying a monthly
data storage fee, and be expecting to run calculations in the cloud too.

Given UQ is big enough to host servers locally, it may be much cheaper
to work on UQ servers. UQ servers are provided as part of research
support too, so as a lab we don't even pay full price for UQ servers.

**Comment by jaseeverett** [comment]
Closing this since we have had the meeting and have a way forward for the moment.
